name: Scheduler Weekly

on:
  # cron runs weekly at 07:13 UTC on Sunday = 03:13 New York time
  schedule:
    - cron: '13 7 * * SUN'
  # manually trigger the workflow
  workflow_dispatch:

jobs:
  Download-NYC-Crash-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Show Python Version
        run: python --version
      - name: Install pip libraries
        run: pip install --upgrade -r requirements-github-actions.txt
      - name: Run python script to download latest CSV data from NYC Open Data
        run: python github_action.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_BRANCH: ${{ github.ref_name }}
